dist: xenial
language: python
python: 3.7
services: xvfb
addons:
  apt:
    update: true
    packages:
    # - ffmpeg
    - freeglut3-dev
    # - python3-gi
    # - python3-gi-cairo
    # - python-gst-1.0
before_install: pip install --upgrade pip flake8 pytest
install: python setup.py install
before_script: flake8 . --count --exclude=./.*,*/future/* --select=E9,F63,F7,F82 --show-source --statistics || true
script: pytest
# after_success: coveralls
